"""schema iniziale

Revision ID: a49e5eab0b9b
Revises:
Create Date: 2026-08-28 13:57:09.142442+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a49e5eab0b9b"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "candidate_profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("full_name", sa.String(length=200), nullable=False),
        sa.Column("email", sa.String(length=320), nullable=False),
        sa.Column("phone", sa.String(length=40), nullable=True),
        sa.Column("city", sa.String(length=120), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column("linkedin_url", sa.String(length=512), nullable=True),
        sa.Column("github_url", sa.String(length=512), nullable=True),
        sa.Column("portfolio_url", sa.String(length=512), nullable=True),
        sa.Column("work_authorization", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("willing_to_relocate", sa.Boolean(), nullable=False),
        sa.Column("notice_period_days", sa.Integer(), nullable=True),
        sa.Column("salary_expectation_min", sa.Integer(), nullable=True),
        sa.Column("salary_expectation_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=False),
        sa.Column("languages", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("ats_answers", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_candidate_profile_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_candidate_profile")),
    )
    op.create_table(
        "job",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=400), nullable=False),
        sa.Column("company", sa.String(length=300), nullable=False),
        sa.Column("company_normalized", sa.String(length=300), nullable=False),
        sa.Column("canonical_key", sa.String(length=600), nullable=False),
        sa.Column("simhash", sa.BigInteger(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=False),
        sa.Column("location_raw", sa.String(length=400), nullable=True),
        sa.Column("city", sa.String(length=160), nullable=True),
        sa.Column("region", sa.String(length=160), nullable=True),
        sa.Column("country", sa.String(length=2), nullable=True),
        sa.Column(
            "work_mode",
            sa.Enum(
                "on_site",
                "hybrid",
                "remote",
                "unknown",
                name="workmode",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("salary_is_stated", sa.Boolean(), nullable=False),
        sa.Column("salary_min", sa.Integer(), nullable=True),
        sa.Column("salary_max", sa.Integer(), nullable=True),
        sa.Column("salary_currency", sa.String(length=3), nullable=True),
        sa.Column(
            "salary_period",
            sa.Enum(
                "hourly",
                "daily",
                "monthly",
                "yearly",
                name="salaryperiod",
                native_enum=False,
                length=32,
            ),
            nullable=True,
        ),
        sa.Column("salary_eur_year_min", sa.Integer(), nullable=True),
        sa.Column("salary_eur_year_max", sa.Integer(), nullable=True),
        sa.Column(
            "contract_type",
            sa.Enum(
                "permanent",
                "fixed_term",
                "contract",
                "internship",
                "apprenticeship",
                "part_time",
                "unknown",
                name="contracttype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "seniority",
            sa.Enum(
                "intern",
                "junior",
                "mid",
                "senior",
                "lead",
                "principal",
                "unknown",
                name="seniority",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("job_family", sa.String(length=120), nullable=True),
        sa.Column("description_raw", sa.Text(), nullable=True),
        sa.Column("description_clean", sa.Text(), nullable=False),
        sa.Column("lang", sa.String(length=5), nullable=True),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("apply_url", sa.String(length=1024), nullable=True),
        sa.Column(
            "ats_type",
            sa.Enum(
                "greenhouse",
                "lever",
                "ashby",
                "workable",
                "recruitee",
                "smartrecruiters",
                "workday",
                "taleo",
                "other",
                "unknown",
                name="atstype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("ats_board_token", sa.String(length=200), nullable=True),
        sa.Column("ats_job_id", sa.String(length=200), nullable=True),
        sa.Column("posted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job")),
    )
    op.create_index("ix_job_active_posted", "job", ["is_active", "posted_at"], unique=False)
    op.create_index("ix_job_canonical_key", "job", ["canonical_key"], unique=False)
    op.create_index("ix_job_company_norm", "job", ["company_normalized"], unique=False)
    op.create_table(
        "profile",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("master_profile", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("raw_text", sa.Text(), nullable=False),
        sa.Column("source_file_name", sa.String(length=255), nullable=False),
        sa.Column("source_storage_path", sa.String(length=512), nullable=True),
        sa.Column("embedding", sa.LargeBinary(), nullable=True),
        sa.Column("embedding_model", sa.String(length=128), nullable=True),
        sa.Column("embedding_dim", sa.Integer(), nullable=True),
        sa.Column("reviewed", sa.Boolean(), nullable=False),
        sa.Column("reviewed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_profile_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_profile")),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("description", sa.String(length=300), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_settings")),
    )
    op.create_table(
        "source",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("adapter", sa.String(length=64), nullable=False),
        sa.Column("display_name", sa.String(length=128), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("config", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("rate_limit_per_min", sa.Integer(), nullable=False),
        sa.Column("daily_call_budget", sa.Integer(), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_source")),
        sa.UniqueConstraint("adapter", name=op.f("uq_source_adapter")),
    )
    op.create_table(
        "task",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column(
            "task_type",
            sa.Enum(
                "run_pipeline",
                "generate_cv",
                "apply",
                "reparse_profile",
                "check_email",
                name="tasktype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "pending",
                "running",
                "done",
                "failed",
                "cancelled",
                name="taskstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("progress", sa.SmallInteger(), nullable=False),
        sa.Column("progress_message", sa.String(length=300), nullable=True),
        sa.Column("result", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("claimed_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("attempts", sa.SmallInteger(), nullable=False),
        sa.Column("max_attempts", sa.SmallInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_task")),
    )
    op.create_index(
        "ix_task_pending",
        "task",
        ["created_at"],
        unique=False,
        postgresql_where=sa.text("status = 'pending'"),
    )
    op.create_index("ix_task_status_created", "task", ["status", "created_at"], unique=False)
    op.create_table(
        "worker_heartbeat",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("version", sa.String(length=32), nullable=True),
        sa.Column("hostname", sa.String(length=128), nullable=True),
        sa.Column("last_run_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "last_run_status",
            sa.Enum(
                "running", "ok", "partial", "failed", name="runstatus", native_enum=False, length=32
            ),
            nullable=True,
        ),
        sa.CheckConstraint("id = 1", name=op.f("ck_worker_heartbeat_singleton")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_worker_heartbeat")),
    )
    op.create_table(
        "job_requirements",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("must_have", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("nice_to_have", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("tech_stack", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("min_years_experience", sa.Integer(), nullable=True),
        sa.Column("max_years_experience", sa.Integer(), nullable=True),
        sa.Column("languages_required", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("remote_policy", sa.String(length=300), nullable=True),
        sa.Column("requires_work_authorization", sa.Boolean(), nullable=True),
        sa.Column("red_flags", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("extracted_with", sa.String(length=128), nullable=False),
        sa.Column("extracted_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_job_requirements_job_id_job"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_requirements")),
        sa.UniqueConstraint("job_id", name=op.f("uq_job_requirements_job_id")),
    )
    op.create_table(
        "job_source_link",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=False),
        sa.Column("external_id", sa.String(length=300), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=False),
        sa.Column("fetched_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("raw", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_job_source_link_job_id_job"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_job_source_link_source_id_source")
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_job_source_link")),
        sa.UniqueConstraint("source_id", "external_id", name="uq_source_external"),
    )
    op.create_index(op.f("ix_job_source_link_job_id"), "job_source_link", ["job_id"], unique=False)
    op.create_table(
        "match",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("job_id", sa.Integer(), nullable=False),
        sa.Column("semantic_score", sa.Float(), nullable=True),
        sa.Column("keyword_score", sa.Float(), nullable=True),
        sa.Column("hybrid_score", sa.Float(), nullable=True),
        sa.Column("score", sa.SmallInteger(), nullable=True),
        sa.Column("subscores", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("rationale", sa.Text(), nullable=True),
        sa.Column("gaps", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("scored_with", sa.String(length=128), nullable=True),
        sa.Column("scored_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("reached_stage", sa.SmallInteger(), nullable=False),
        sa.Column("filtered_reason", sa.String(length=200), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "new",
                "seen",
                "shortlist",
                "hidden",
                "applied",
                name="matchstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["job_id"], ["job.id"], name=op.f("fk_match_job_id_job"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_match")),
        sa.UniqueConstraint("job_id", name=op.f("uq_match_job_id")),
    )
    op.create_index("ix_match_score_status", "match", ["score", "status"], unique=False)
    op.create_index(op.f("ix_match_status"), "match", ["status"], unique=False)
    op.create_index("ix_match_status_created", "match", ["status", "created_at"], unique=False)
    op.create_table(
        "run",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("batch_id", sa.String(length=36), nullable=False),
        sa.Column("source_id", sa.Integer(), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "running", "ok", "partial", "failed", name="runstatus", native_enum=False, length=32
            ),
            nullable=False,
        ),
        sa.Column("started_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("finished_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("jobs_fetched", sa.Integer(), nullable=False),
        sa.Column("jobs_new", sa.Integer(), nullable=False),
        sa.Column("jobs_duplicate", sa.Integer(), nullable=False),
        sa.Column("api_calls", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(
            ["source_id"], ["source.id"], name=op.f("fk_run_source_id_source"), ondelete="SET NULL"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_run")),
    )
    op.create_index(op.f("ix_run_batch_id"), "run", ["batch_id"], unique=False)
    op.create_index("ix_run_started", "run", ["started_at"], unique=False)
    op.create_table(
        "application",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("match_id", sa.Integer(), nullable=False),
        sa.Column(
            "tier",
            sa.Enum(
                "a_auto",
                "b_assisted",
                "c_manual",
                name="applicationtier",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column(
            "status",
            sa.Enum(
                "draft",
                "cv_ready",
                "approved",
                "needs_human",
                "submitted",
                "failed",
                "withdrawn",
                "acknowledged",
                "interview",
                "rejected",
                "offer",
                name="applicationstatus",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("cv_storage_path", sa.String(length=512), nullable=True),
        sa.Column("cover_letter_storage_path", sa.String(length=512), nullable=True),
        sa.Column("cv_payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("cv_language", sa.String(length=5), nullable=True),
        sa.Column("cv_fit_iterations", sa.Integer(), nullable=True),
        sa.Column("submitted_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("was_dry_run", sa.Boolean(), nullable=False),
        sa.Column("ats_response", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("screenshots", postgresql.ARRAY(sa.String()), nullable=False),
        sa.Column("follow_up_due_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_email_checked_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["match_id"],
            ["match.id"],
            name=op.f("fk_application_match_id_match"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application")),
        sa.UniqueConstraint("match_id", name=op.f("uq_application_match_id")),
    )
    op.create_index(op.f("ix_application_status"), "application", ["status"], unique=False)
    op.create_index(
        "ix_application_status_submitted", "application", ["status", "submitted_at"], unique=False
    )
    op.create_table(
        "application_event",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("application_id", sa.Integer(), nullable=False),
        sa.Column(
            "event_type",
            sa.Enum(
                "created",
                "cv_generated",
                "approved",
                "submitted",
                "submit_failed",
                "email_received",
                "status_changed",
                "follow_up_due",
                name="applicationeventtype",
                native_enum=False,
                length=32,
            ),
            nullable=False,
        ),
        sa.Column("occurred_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.ForeignKeyConstraint(
            ["application_id"],
            ["application.id"],
            name=op.f("fk_application_event_application_id_application"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_application_event")),
    )
    op.create_index(
        op.f("ix_application_event_application_id"),
        "application_event",
        ["application_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_application_event_application_id"), table_name="application_event")
    op.drop_table("application_event")
    op.drop_index("ix_application_status_submitted", table_name="application")
    op.drop_index(op.f("ix_application_status"), table_name="application")
    op.drop_table("application")
    op.drop_index("ix_run_started", table_name="run")
    op.drop_index(op.f("ix_run_batch_id"), table_name="run")
    op.drop_table("run")
    op.drop_index("ix_match_status_created", table_name="match")
    op.drop_index(op.f("ix_match_status"), table_name="match")
    op.drop_index("ix_match_score_status", table_name="match")
    op.drop_table("match")
    op.drop_index(op.f("ix_job_source_link_job_id"), table_name="job_source_link")
    op.drop_table("job_source_link")
    op.drop_table("job_requirements")
    op.drop_table("worker_heartbeat")
    op.drop_index("ix_task_status_created", table_name="task")
    op.drop_index(
        "ix_task_pending", table_name="task", postgresql_where=sa.text("status = 'pending'")
    )
    op.drop_table("task")
    op.drop_table("source")
    op.drop_table("settings")
    op.drop_table("profile")
    op.drop_index("ix_job_company_norm", table_name="job")
    op.drop_index("ix_job_canonical_key", table_name="job")
    op.drop_index("ix_job_active_posted", table_name="job")
    op.drop_table("job")
    op.drop_table("candidate_profile")
    # ### end Alembic commands ###
